
# use the official python image from the docker hub
FROM python:3.10-slim
#set the work directory in the container
WORKDIR /app
#copy the requirements file to the container
COPY requirements.txt .
#install the dependencies
RUN pip install -r requirements.txt
#copy the application code to the container
COPY . .
#run the application
CMD ["python", "app.py"]